#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_38
#define AUDIO_I2S_GPIO_WS GPIO_NUM_13
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_11
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_12

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_42
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR


#define BUILTIN_LED_GPIO        GPIO_NUM_10
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define PWR_BUTTON_GPIO         GPIO_NUM_3
#define PWR_EN_GPIO             GPIO_NUM_5
#define PWR_ADC_GPIO            GPIO_NUM_4
#define PWR_BUTTON_TIME         3000000U

#define WIFI_BUTTON_GPIO        GPIO_NUM_6
#define CMD_BUTTON_GPIO         GPIO_NUM_7


#define DISPLAY_SPI_SCK_PIN     GPIO_NUM_41
#define DISPLAY_SPI_MOSI_PIN    GPIO_NUM_40
#define DISPLAY_DC_PIN          GPIO_NUM_39
#define DISPLAY_SPI_CS_PIN      GPIO_NUM_9

#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  320
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_46
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#ifdef CONFIG_SD_CARD_MMC_INTERFACE

// Define to use 4-bit SDMMC bus width; comment out to use 1-bit bus width
//#define CARD_SDMMC_BUS_WIDTH_4BIT

#ifdef CARD_SDMMC_BUS_WIDTH_4BIT
#define CARD_SDMMC_CLK_GPIO GPIO_NUM_40 // CLK pin
#define CARD_SDMMC_CMD_GPIO GPIO_NUM_39 // MISO pin
#define CARD_SDMMC_D0_GPIO GPIO_NUM_41  // MOSI pin
#define CARD_SDMMC_D1_GPIO GPIO_NUM_42
#define CARD_SDMMC_D2_GPIO GPIO_NUM_45
#define CARD_SDMMC_D3_GPIO GPIO_NUM_38  // CS pin
#else // Chọn cấu hình SDCard 1 bit
#define CARD_SDMMC_CLK_GPIO GPIO_NUM_47
#define CARD_SDMMC_CMD_GPIO GPIO_NUM_48
#define CARD_SDMMC_D0_GPIO GPIO_NUM_21
#endif
#endif // CONFIG_SD_CARD_MMC_INTERFACE


#endif // _BOARD_CONFIG_H_
